sudo: false
language: node_js
node_js: "6"
before_install:
- ./firefox-allow-popups.sh
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != false ]; then SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY_NOT_MASTER SAUCE_USERNAME=$SAUCE_USERNAME_NOT_MASTER; fi
- echo "Sauce Labs username is $SAUCE_USERNAME"
- |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^docs)|(^demos)/'
    then
      echo "Only docs were updated, skipping tests."
      exit
    fi
- "echo 'This is running'"
after_install:
- "echo 'Install has finished'"
env:
  - TEST_SUITE=sauce-labs
  - TEST_SUITE=development
  - TEST_SUITE=production
  - TEST_SUITE=builders
  - TEST_SUITE=global-build
script:
  - "npm run test-$TEST_SUITE"
before_script:
  - npm run http-server &
  - sleep 2
addons:
  hosts: canjs.test
  sauce_connect: true
  firefox: latest
